### PR TITLE
Warren scrimmage worlds

### LINKED ISSUE #328: Depot auton
Finish and test an auton that picks up fuel from the depot and scores them

### LINKED ISSUE #455: Fix passing bug
Current passing code always sets the top/bottom roller speeds to 0. Pls fix

Image

The io.runShooterWithSpeeds(topSpeed, bottomSpeed); along with top/bottom speed variable initialization should be inside the if statement

### LINKED ISSUE #457: increase speed on the intake
The intake roller speed is currently at half speed (for tuning purposes). Make it as fast as possible without us chucking fuel outside of the robot (probably start at theoretical max?)

### LINKED ISSUE #458: Add second pass + second shooting period to scoop autons
Replace existing intaking paths so it goes up against the bump, then fans out back to the trench. On the outpost side, continue intaking even driving under the trench to the second shooting period (since we're driving intake-first there)

Add a second shooting period

### LINKED ISSUE #459: X boundaries for red and blue are wrong -> will cause unintended passing and break shooting
Maybe a clickbait title, but the boundaries are stricter than they need to be and could break shooting from inside the trench.

The boundaries are currently this:

Image

and should probably be the same as the x-value for the hub poses

Image

### LINKED ISSUE #462: Add Boolean value logging if vision estimate is present
In VisionPoseEstimator.periodoc, add the logging of a boolean that indicates if a pose estimate came from vision.

e.g.

```
    private final BooleanPublisher visionPoseExistsPublisher;
    private boolean visionPoseExists = false;

```

In constructor

```
        visionPoseExistsPublisher =
                NetworkTableInstance.getDefault()
                        .getBooleanTopic("VisionPoseEstimator/visionPoseExists")
                        .publish();



```
In periodic
```
     this.visionPoseExists = false ;
        getPoseEstimate(limelightNameMain)
                .ifPresent(
                        (pe) -> {
                            visionPoseExists = true;
                            mt2PublisherMain.set(pe.pose);
                            // LimelightHelpers doesn't expose a helper method for these, layout is:
                            // [MT1x, MT1y, MT1z, MT1roll, MT1pitch, MT1Yaw, MT2x, MT2y, MT2z,
                            // MT2roll,
                            // MT2pitch, MT2yaw]
                            var stddevs =
                                    LimelightHelpers.getLimelightNTDoubleArray(
                                            limelightHostnameMain, "stddevs");
                            driveBase.addVisionMeasurement(
                                    pe.pose,
                                    pe.timestampSeconds,
                                    VecBuilder.fill(
                                            stddevs[6], stddevs[7], Double.POSITIVE_INFINITY));
                        });
    
```

### PR DESCRIPTION
**Pull request by mhoughton26**
## Description

Briefly describe the purpose of this pull request and the changes made. 

## Testing

Describe the steps taken to test your changes.

## Checklist

*  [ ] Performed a self-review of my code
*  [ ] Commented my code
*  [ ] My code follows the 2399 coding standards
*  [ ] Merged in the main branch and fixed any merge conflicts
*  [ ] Built code with no errors
*  [ ] Tested code
*  [ ] Formatted code with spotless ( ./gradlew spotlessApply )
*  [ ] Added and committed all code changes
*  [ ] Pushed code to github
*  [ ] Linked this PR to the issue it is associated with using the gear icon next to Development on the right side of this PR page

### CODE REVIEW

File: src/main/java/frc/robot/subsystems/shooter/ShooterSubsystem.java [hunk 1]
```diff
@@ -95,7 +113,40 @@ public Command shoot(
                                                     bottomShooterSpeedTreeMapMeterRadS.get(
                                                             distFromTarget.get().in(Meters)));
                                 } else {
-                                    io.pass(distFromTarget);
+                                    // point slope form: y-y1 = m(x-x1) => y = m(x-x1) + y1
+                                    topSpeed =
```
Comment (beccawilcox001) [inline src/main/java/frc/robot/subsystems/shooter/ShooterSubsystem.java:116]: this refactor makes things a lot clearer; thanks for doing it!
