### PR TITLE
fixed roller gear ratio for tuning intake rollers

### LINKED ISSUE #414: Retune intake rollers
Will need to look at kS and kV after putting the second intake motor on. Then alter p if necessary

### PR DESCRIPTION
**Pull request by vivianqii**
## Description

Briefly describe the purpose of this pull request and the changes made. 

## Testing

Describe the steps taken to test your changes.

## Checklist

*  [ ] Performed a self-review of my code
*  [ ] Commented my code
*  [ ] My code follows the 2399 coding standards
*  [ ] Merged in the main branch and fixed any merge conflicts
*  [ ] Built code with no errors
*  [ ] Tested code
*  [ ] Formatted code with spotless ( ./gradlew spotlessApply )
*  [ ] Added and committed all code changes
*  [ ] Pushed code to github
*  [ ] Linked this PR to the issue it is associated with using the gear icon next to Development on the right side of this PR page

### CODE REVIEW

**Review by hschilling — CHANGES_REQUESTED** [review]
Looks good but need to change the kv 


```
private static final double DEFAULT_INTAKE_KV =
    12 / (RobotConstants.MotorConstants.VORTEX_FREE_SPEED.in(RadiansPerSecond) / ROLLER_GEAR_RATIO);
```

**Review by baheyaqoran — COMMENTED** [review]
Looks good, listen to Herb!

File: src/main/java/frc/robot/subsystems/intake/IntakeRollerHardware.java [hunk 1]
```diff
@@ -134,8 +133,7 @@ public void setZero() {
     public void updateState(IntakeRollerIOState state) {
         state.leaderActualSpeedRadiansPerSecond = intakeLeaderEncoder.getVelocity();
         state.followerActualSpeedRadiansPerSecond = intakeFollowerEncoder.getVelocity();
-        state.desiredSpeedRadiansPerSecond =
-                desiredVelocity.in(RadiansPerSecond) / ROLLER_GEAR_RATIO;
+        state.desiredSpeedRadiansPerSecond = desiredVelocity.in(RadiansPerSecond) / 2;
```
Comment (beccawilcox001) [inline src/main/java/frc/robot/subsystems/intake/IntakeRollerHardware.java]: should get rid of this /2 -> this was added so we could tune kV correctly

**Review by beccawilcox001 — APPROVED** [review]

**Comment by beccawilcox001** [comment]
the kv was tuned empirically!

**Comment by beccawilcox001** [comment]
the kv was tuned empirically!
