### PR TITLE
Fix spindexer

### LINKED ISSUE #398: Feedforward not working in spindexer and other spindexer issues
# Feedforward not working

The plot of desired and actual speeds and also the voltage of the spindexer shows that feedforward is not happening. This plot is from E12 of MVR. 

Image

When the desired speed is set, the voltage should immediately jump ( or close to it since we have a ramp rate of 0.1 sec) to some level. The plot indicates that only PID is happening and since the P is so low, it takes a long time to gradually get to the setpoint. 

The current code has

```
spindexClosedLoopConfig.feedForward.sva(SPINDEXER_KS, SPINDEXER_KV, 0);
spindexerSparkFlexConfig.apply(spindexClosedLoopConfig);
```

which seems reasonable? But can also try just doing this

```
        spindexerSparkFlexConfig.closedLoop.feedForward.sva(SPINDEXER_KS, SPINDEXER_KV, 0);
```

If that does not work, look to other methods to do feedforward with the REV API since the `sva` method is not widely used or even documented by REV. 

# Setting feedforward

Looking at the plots, specifically actual speed versus voltage, the kV value looks like it should be something like 6/34= ~ 0.17. The current value is much lower than that. 

# PID tuning

Might want to disable the ramp rate for this.

Once feedforward is fixed, revisit the setting of the P value. P has units so a good initial value can be calculated. P should be sized to correct typical errors with reasonable voltage changes. 

1. Run the system with only feedforward (P = 0)
2. Look at plots to measure the steady-state velocity error in radians per second
3. Decide how much P to correct this. Even a guess of 0.1 V might be a good starting point just to the order of magnitude correct
4. Calculate initial P = voltage change from step 3 divided by the error from step 2

Then do the usual 
- If it oscillates: P is too high → cut in half
- If it's too sluggish: P is too low → double it
- If it overshoots once then settles: just right or slightly high

# desiredVelocity calculation needs correction

The current code has

```
desiredVelocity = RadiansPerSecond.of(
    0.085 * SPINDEXER_GEAR_RATIO * MotorConstants.VORTEX_FREE_SPEED.in(RadiansPerSecond));
```
But the gear ratio should be divided by, not multiplied by. That is why we have to use such a small value `0.085` to be the fraction of max speed we want. If you divide by the gear ration, then that number can be between 0.0 and 1.0 

# runSpindexerBackwards missing gear ratio

The `runSpindexerBackwards` method is missing the gear ratio. Should be like for the corrected `runSpindexer`

# Brake mode ?
For an indexer would it be better to be in brake mode so we accidentally don't shoot balls after the driver wants shooting to stop? This might not be good for the mechanism though?

# Ramp rate?
Tune the ramp rate.

# Stall detection?

Might be helpful to detect stalling? Could this potentially save a motor and also warn the driver

### PR DESCRIPTION
**Pull request by mhoughton26**
## Description

Briefly describe the purpose of this pull request and the changes made. 

## Testing

Describe the steps taken to test your changes.

## Checklist

*  [ ] Performed a self-review of my code
*  [ ] Commented my code
*  [ ] My code follows the 2399 coding standards
*  [ ] Merged in the main branch and fixed any merge conflicts
*  [ ] Built code with no errors
*  [ ] Tested code
*  [ ] Formatted code with spotless ( ./gradlew spotlessApply )
*  [ ] Added and committed all code changes
*  [ ] Pushed code to github
*  [ ] Linked this PR to the issue it is associated with using the gear icon next to Development on the right side of this PR page

### CODE REVIEW

File: src/main/java/frc/robot/SubsystemFactory.java [hunk 1]
```diff
@@ -99,7 +99,8 @@ public DriveSubsystem buildDriveSubsystem(Gyro gyro) {
         if (robotType == RobotType.BETA
                 || robotType == RobotType.BUBBLES
                 || robotType == RobotType.MOZART
-                || robotType == RobotType.COMP) {
+        // || robotType == RobotType.COMP
```
Comment (beccawilcox001) [inline src/main/java/frc/robot/SubsystemFactory.java]: fix this pls

**Comment by beccawilcox001** [comment]
looks good, but should test on the robot before merging to main

**Review by hschilling — APPROVED** [review]
